language: android
sudo: required
jdk:
  - oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-26
    - extra-android-m2repository

install: 
  - echo y | sdkmanager 'ndk-bundle' 
  - echo y | sdkmanager 'cmake;3.6.4111459' 
  - echo y | sdkmanager 'lldb;3.0'

script:
  - ./gradlew dependencyCheckAnalyze build connectedCheck

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"